# Generated by Django 3.0.5 on 2020-06-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='SIN NOMBRE', max_length=10)),
                ('apellidos', models.CharField(default='SIN NOMBRE', max_length=10)),
            ],
        ),
    ]
