# Generated by Django 3.0.5 on 2020-06-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacioon1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellidos', models.CharField(default='SIN NOMBRE', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=18),
        ),
    ]
