# Generated by Django 3.0.5 on 2020-06-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacioon1', '0002_auto_20200620_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='-', max_length=254),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=10),
        ),
    ]
