# Generated by Django 3.0.5 on 2020-06-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacioon1', '0003_auto_20200620_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cedula',
            field=models.CharField(default='0912345678', max_length=10),
        ),
    ]
