# Generated by Django 3.0.5 on 2020-06-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacioon1', '0004_persona_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(default='SIN NOMBRE', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=100),
        ),
    ]
